# Generated by Django 5.2 on 2025-06-11 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="profile_pics/default-avatar.png",
                        upload_to="profile_pics",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("semester_credit_load", models.IntegerField()),
                ("sleep_quality", models.CharField(max_length=10)),
                ("physical_activity", models.CharField(max_length=10)),
                ("diet_quality", models.CharField(max_length=10)),
                ("social_support", models.CharField(max_length=10)),
                ("relationship_status", models.CharField(max_length=10)),
                ("financial_stress", models.IntegerField()),
                (
                    "substance_use",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "counseling_service_use",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "family_history",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "chronic_illness",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "extracurricular_involvement",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "residence_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stress_level", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "depression_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("anxiety_score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "predict_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.userresponse",
                    ),
                ),
            ],
        ),
    ]
